### PR TITLE
Transaction list

### PR DESCRIPTION
**Pull request by boazberman**

### CODE REVIEW

**Comment by boazberman** [comment]
I squashed my commits, so it might be a bit off to you @svechinsky but it is same as it was plus the requested modifications.

**Comment by boazberman** [comment]
Also waiting for @svechinsky to decide which of the Footers are the one to be used, so I can resolve the merge conflict...

**Comment by boazberman** [comment]
@svechinsky Rebased against master, ready for approval.

**Comment by svechinsky** [comment]
Hooray, Merging

**Pull request merged**
